### ISSUE TITLE
set_logger function no longer exposed

### ISSUE THREAD

**Issue by MartinHowarth** [Metaswitch/cassandra-rs#149]
My cargo.toml includes:
```
cassandra-cpp = { git = "https://github.com/Metaswitch/cassandra-rs", features = ["early_access_min_tls_version"] }
```

and compilation now fails with:
```
error[E0432]: unresolved import `cassandra_cpp::set_logger`
...
no `set_logger` in the root
```
It fails even if I add in `slog` or `log` or `default` in the features.

I think the problem was introduced in https://github.com/Metaswitch/cassandra-rs/pull/146

I can workaround by importing `set_slog_logger`, but wanted to raise that there has been a breaking change.

**Comment by kw217** [comment]
Thanks @MartinHowarth for the report, and for testing this before it's been tagged.

@rukai any chance you could take a look? I'm not sure what's gone wrong here; adding `slog` to the feature was certainly intended to expose `set_logger`.
